// @title           Tutor Desk API
// @version         1.0
// @description     REST API for Tutor Desk — exam management platform for teachers and students.
// @termsOfService  http://tutordesk.app/terms

// @contact.name   Tutor Desk Support
// @contact.email  support@tutordesk.app

// @license.name  MIT

// @host      localhost:8080
// @BasePath  /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer " followed by your access_token from POST /api/v1/auth/login

// @tag.name Auth
// @tag.description Login, signup, token refresh and password management
// @tag.name Users
// @tag.description User profile operations
// @tag.name Teachers
// @tag.description Teacher management (super_admin) and teacher self-service
// @tag.name Students
// @tag.description Student management by teachers
// @tag.name Subjects
// @tag.description Subject CRUD and enrollment management
// @tag.name Exams
// @tag.description Exam lifecycle and assignment operations
// @tag.name Questions
// @tag.description MCQ question management within exams
// @tag.name Submissions
// @tag.description Exam-taking lifecycle — start, answer, submit, evaluate
// @tag.name Assets
// @tag.description Subject learning material uploads and management
// @tag.name Comments
// @tag.description Comments on subject assets
// @tag.name Admin
// @tag.description Super-admin dashboard and reporting
// @tag.name Settings
// @tag.description System settings categories and key-value configuration

package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "github.com/tutor-desk/api/docs" // generated by swag init

	"github.com/tutor-desk/api/internal/config"
	"github.com/tutor-desk/api/internal/database"
	"github.com/tutor-desk/api/internal/router"
)

func main() {
	cfg := config.Load()

	ctx := context.Background()
	db, err := database.NewPool(ctx, cfg)
	if err != nil {
		log.Fatalf("database connection error: %v", err)
	}
	defer db.Close()
	log.Println("database connected")

	if err := os.MkdirAll(cfg.UploadDir, 0755); err != nil {
		log.Fatalf("failed to create upload directory: %v", err)
	}

	handler := router.New(db, cfg)

	addr := fmt.Sprintf(":%s", cfg.Port)
	srv := &http.Server{
		Addr:         addr,
		Handler:      handler,
		ReadTimeout:  time.Duration(cfg.ServerReadTimeoutS) * time.Second,
		WriteTimeout: time.Duration(cfg.ServerWriteTimeoutS) * time.Second,
		IdleTimeout:  time.Duration(cfg.ServerIdleTimeoutS) * time.Second,
	}

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		log.Printf("server starting on %s", addr)
		log.Printf("swagger UI: http://localhost%s/swagger/", addr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("server error: %v", err)
		}
	}()

	<-quit
	log.Println("shutting down server...")

	shutCtx, cancel := context.WithTimeout(context.Background(), time.Duration(cfg.ServerShutdownTimeoutS)*time.Second)
	defer cancel()

	if err := srv.Shutdown(shutCtx); err != nil {
		log.Printf("server forced to shutdown: %v", err)
	}
	log.Println("server stopped")
}
